package pl.kolendateam.dadcard.modifier.entity;

public enum ModifierEnum {
  ABILITY_MODIFIER,
  ALCHEMICAL_BONUS,
  ARMOR_BONUS,
  CIRCUMSTANCE_MODIFIER,
  COMPETENCE_MODIFIER,
  DEFLECTION_BONUS,
  DODGE_BONUS,
  INSIGHT_BONUS,
  LUCK_MODIFIER,
  MORALE_MODIFIER,
  NATURAL_ARMOR_BONUS,
  PROFANE_MODIFIER,
  RACIAL_BONUS,
  RESISTANCE_BONUS,
  SACRED_MODIFIER,
  SHIELD_BONUS,
  SIZE_MODIFIER,
}
