package pl.kolendateam.dadcard.items.armor.entity;

public enum ArmorsEnum {
  NO_ARMOR,
  LIGHT_ARMOR,
  MEDIUM_ARMOR,
  HEAVY_ARMOR,
  NO_SHIELD,
  SHIELD,
  EXTRAS,
  PADDED,
  LEATHER,
  STUDDED_LEATHER,
  CHAIN_SHIRT,
  HIDE,
  SCALE_MAIL,
  CHAINMAIL,
  BREASTPLATE,
  SPLINT_MAIL,
  BANDED_MAIL,
  HALF_PLATE,
  FULL_PLATE,
  BUCKLER,
  SHIELD_LIGHT_WOODEN,
  SHIELD_LIGHT_STEEL,
  SHIELD_HEAVY_WOODEN,
  SHIELD_HEAVY_STEEL,
  SHIELD_TOWER
}
