package pl.kolendateam.dadcard.weapons.entity;

public enum WeaponNameEnum {

    UNARMED_STRIKE("Unarmed_Strike"),
    DAGGER("Dagger"),
    DAGGER_PUNCHING("Dagger_Punching"),
    GAUNTLET_SPIKED("Gauntlet_Spiked"),
    MACE_LIGHT("Mace_Light"),
    SICKLE("Sickle"),
    CLUB("Club"),
    MACE_HEAVY("Mace_Heavy"),
    MORNINGSTAR("Morningstar"),
    SHORTSPEAR("Shortspear"),
    LONGSPEAR("Longspear"),
    QUARTERSTAFF("Quarterstaff"),
    SPEAR("Spear"),
    CROSSBOW_HEAVY("Crossbow_Heavy"),
    BOLT_CROSSBOW("Bolt_Crossbow"),
    CROSSBOW_LIGHT("Crossbow_Light"),
    DART("Dart"),
    JAVELIN("Javelin"),
    SLING("Sling"),
    BULLETS_SLING("Bullets_Sling"),
    AXE_THROWING("Axe_Throwing"),
    HAMMER_LIGHT("Hammer_Light"),
    HANDAXE("Handaxe"),
    KUKRI("Kukri"),
    PICK_LIGHT("Pick_Light"),
    SAP("Sap"),
    SHIELD_LIGHT("Shield_Light"),
    SPIKED_ARMOR("Spiked_Armor"),
    SPIKED_SHIELD_LIGHT("Spiked_Shield_Light"),
    SWORD_SHORT("Sword_Short"),
    BATTLEAXE("Battleaxe"),
    FLAIL("Flail"),
    LONGSWORD("Longsword"),
    PICK_HEAVY("Pick_Heavy"),
    RAPIER("Rapier"),
    SCIMITAR("Scimitar"),
    SHIELD_HEAVY("Shield_Heavy"),
    SPIKED_SHIELD_HEAVY("Spiked_Shield_Heavy"),
    TRIDENT("Trident"),
    WARHAMMER("Warhammer"),
    FALCHION("Falchion"),
    GLAIVE("Glaive"),
    GREATAXE("Greataxe"),
    GREATCLUB("Greatclub"),
    FLAIL_HEAVY("Flail_Heavy"),
    GREATSWORD("Greatsword"),
    GUISARME("Guisarme"),
    HALBERD("Halberd"),
    LANCE("Lance"),
    RANSEUR("Ranseur"),
    SCYTHE("Scythe"),
    LONGBOW("Longbow"),
    ARROW("Arrow"),
    LONGBOW_COMPOSITE("Longbow_Composite"),
    SHORTBOW("Shortbow"),
    SHORTBOW_COMPOSITE("Shortbow_Composite"),
    KAMA("Kama"),
    NUNCHAKU("Nunchaku"),
    SAI("Sai"),
    SIANGHAM("Siangham"),
    SWORD_BASTARD("Sword_Bastard"),
    WARAXE_DWARVEN("Waraxe_Dwarven"),
    WHIP("Whip"),
    AXE_ORC_DOUBLE("Axe_Orc_Double"),
    CHAIN_SPIKED("Chain_Spiked"),
    FLAIL_DIRE("Flail_Dire"),
    HAMMER_GNOME_HOOKED("Hammer_Gnome_Hooked"),
    SWORD_TWO_BLADED("Sword_Two_Bladed"),
    URGROSH_DWARVEN("Urgrosh_Dwarven"),
    BOLAS("Bolas"),
    CROSSBOW_HAND("Crossbow_Hand"),
    CROSSBOW_REPEATING_HEAVY("Crossbow_Repeating_Heavy"),
    CROSSBOW_REPEATING_LIGHT("Crossbow_Repeating_Light"),
    NET("Net"),
    SHURIKEN("Shuriken");

    private String weaponNameEnum;

    public String getWeaponNameEnum(){
        return weaponNameEnum;
    }

    private WeaponNameEnum(String weaponNameEnum){
        this.weaponNameEnum = weaponNameEnum; 
    }
    
}
