INSERT INTO Skills values('Appraise');
INSERT INTO Skills values('Balance');
INSERT INTO Skills values('Bluff');
INSERT INTO Skills values('Climb');
INSERT INTO Skills values('Concentration');
INSERT INTO Skills values('Craft');
INSERT INTO Skills values('Decipher Script');
INSERT INTO Skills values('Diplomacy');
INSERT INTO Skills values('Disable Device');
INSERT INTO Skills values('Disguise');
INSERT INTO Skills values('Escape Artist');
INSERT INTO Skills values('Gather Information');
INSERT INTO Skills values('Handle Animal');
INSERT INTO Skills values('Heal');
INSERT INTO Skills values('Intimidate');
INSERT INTO Skills values('Jump');
INSERT INTO Skills values('Knowledge');
INSERT INTO Skills values('Listen');
INSERT INTO Skills values('Move Silently');
INSERT INTO Skills values('Perform');
INSERT INTO Skills values('Profession');
INSERT INTO Skills values('Ride');
INSERT INTO Skills values('Search');
INSERT INTO Skills values('Sense Motive');
INSERT INTO Skills values('Sleight Of Hand');
INSERT INTO Skills values('Speak Language');
INSERT INTO Skills values('Spellcraft');
INSERT INTO Skills values('Spot');
INSERT INTO Skills values('Survival');
INSERT INTO Skills values('Swim');
INSERT INTO Skills values('Tumble');
INSERT INTO Skills values('Use Magic Device');
INSERT INTO Skills values('Use Rope');