INSERT INTO Skills values skillsName ('Appraise');
INSERT INTO Skills values skillsName ('Balance');
INSERT INTO Skills values skillsName ('Bluff');
INSERT INTO Skills values skillsName ('Climb');
INSERT INTO Skills values skillsName ('Concentration');
INSERT INTO Skills values skillsName ('Craft');
INSERT INTO Skills values skillsName ('Decipher Script');
INSERT INTO Skills values skillsName ('Diplomacy');
INSERT INTO Skills values skillsName ('Disable Device');
INSERT INTO Skills values skillsName ('Disguise');
INSERT INTO Skills values skillsName ('Escape Artist');
INSERT INTO Skills values skillsName ('Gather Information');
INSERT INTO Skills values skillsName ('Handle Animal');
INSERT INTO Skills values skillsName ('Heal');
INSERT INTO Skills values skillsName ('Intimidate');
INSERT INTO Skills values skillsName ('Jump');
INSERT INTO Skills values skillsName ('Knowledge');
INSERT INTO Skills values skillsName ('Listen');
INSERT INTO Skills values skillsName ('Move Silently');
INSERT INTO Skills values skillsName ('Perform');
INSERT INTO Skills values skillsName ('Profession');
INSERT INTO Skills values skillsName ('Ride');
INSERT INTO Skills values skillsName ('Search');
INSERT INTO Skills values skillsName ('Sense Motive');
INSERT INTO Skills values skillsName ('Sleight Of Hand');
INSERT INTO Skills values skillsName ('Speak Language');
INSERT INTO Skills values skillsName ('Spellcraft');
INSERT INTO Skills values skillsName ('Spot');
INSERT INTO Skills values skillsName ('Survival');
INSERT INTO Skills values skillsName ('Swim');
INSERT INTO Skills values skillsName ('Tumble');
INSERT INTO Skills values skillsName ('Use Magic Device');
INSERT INTO Skills values skillsName ('Use Rope');