CREATE TABLE modAbilities(
    modAbilitiesId serial PRIMARY KEY,
    abilities INT,
    modAbilities INT,
    bonusSpell1 INT,
    bonusSpell2 INT,
    bonusSpell3 INT,
    bonusSpell4 INT,
    bonusSpell5 INT,
    bonusSpell6 INT,
    bonusSpell7 INT,
    bonusSpell8 INT,
    bonusSpell9 INT
);

CREATE TABLE pg(
    pgId serial PRIMARY KEY,
	  pgRacesName VARCHAR(100),
      pgSubRacesName VARCHAR(100),
      pgStrenght INT,
      pgModpgStrenght INT,
      pgDextrity INT,
      pgModpgDextrity INT,
      pgConsitution INT,
      pgModpgConsitution INT,
      pgIntelligence INT,
      pgModpgIntelligence INT,
      pgWisdom INT,
      pgModpgWisdom INT,
      pgCharisma INT,
      pgModpgCharisma INT,
      pgBaseAttackBonus INT,
      appraise boolean,
      balance boolean,
      bluff boolean,
      climb boolean,
      concentration boolean,
      craft boolean,
      diplomacy boolean,
      disable_device boolean,
      disguise boolean,
      escape_artist boolean,
      gather_information boolean,
      handle_animal boolean,
      heal boolean,
      intimidate boolean,
      jump boolean,
      knowledge boolean,
      listen boolean,
      move_silently boolean,
      perform boolean,
      profession boolean,
      ride boolean,
      search boolean,
      sense_motive boolean,
      sleight_of_hand boolean,
      spellcraft boolean,
      spot boolean,
      survival boolean,
      swim boolean,
      tumble boolean,
      use_magic_device boolean,
      use_rope boolean
);

CREATE TABLE races(
    racesId serial PRIMARY KEY,
    racesName VARCHAR(100), 
    subRacesName VARCHAR(100),
    strenght INT,
    dextrity INT,
    consitution INT,
    intelligence INT,
    wisdom INT,
    charisma INT,
    appraise double precision,
    balance double precision,
    bluff double precision,
    climb double precision,
    concentration double precision,
    craft double precision,
    diplomacy double precision,
    disable_device double precision,
    disguise double precision,
    escape_artist double precision,
    gather_information double precision,
    handle_animal double precision,
    heal double precision,
    intimidate double precision,
    jump double precision,
    knowledge double precision,
    listen double precision,
    move_silently double precision,
    perform double precision,
    profession double precision,
    ride double precision,
    search double precision,
    sense_motive double precision,
    sleight_of_hand double precision,
    speak_language VARCHAR(100),
    spellcraft double precision,
    spot double precision,
    survival double precision,
    swim double precision,
    tumble double precision,
    use_magic_device double precision,
    use_rope double precision
);

CREATE TABLE skills(
    skills_Id serial PRIMARY KEY,
    skillsName VARCHAR(50)
);

CREATE TABLE classes(
    pgId serial PRIMARY KEY,
    nameClassPg VARCHAR(100),
    prestigeClass boolean,
      pgBaseAttackBonus INT,
      fortitude double precision,
      reflex double precision,
      will double precision,
      skillPoints INT,
      appraise boolean,
      balance boolean,
      bluff boolean,
      climb boolean,
      concentration boolean,
      craft boolean,
      diplomacy boolean,
      disable_device boolean,
      disguise boolean,
      escape_artist boolean,
      gather_information boolean,
      handle_animal boolean,
      heal boolean,
      intimidate boolean,
      jump boolean,
      knowledge boolean,
      listen boolean,
      move_silently boolean,
      perform boolean,
      profession boolean,
      ride boolean,
      search boolean,
      sense_motive boolean,
      sleight_of_hand boolean,
      spellcraft boolean,
      spot boolean,
      survival boolean,
      swim boolean,
      tumble boolean,
      use_magic_device boolean,
      use_rope boolean
);