--liquibase formatted sql
--changeset orzepowski:1

CREATE TABLE pg(
    pg_Id serial PRIMARY KEY,
	  pgRacesName VARCHAR(100),
      pgSubRacesName VARCHAR(100),
      pgStrenght integer,
      pgDextrity integer,
      pgConsitution integer,
      pgIntelligence integer,
      pgWisdom integer,
      pgCharisma integer,
      pgBaseAttackBonus integer
      appraise boolean,
      balance boolean,
      bluff boolean,
      climb boolean,
      concentration boolean,
      craft boolean,
      decipher_script boolean,
      diplomacy boolean,
      disable_device boolean,
      disguise boolean,
      escape_artist boolean,
      gather_information boolean,
      handle_animal boolean,
      heal boolean,
      intimidate boolean,
      jump boolean,
      knowledge boolean,
      listen boolean,
      move_silently boolean,
      perform boolean,
      profession boolean,
      ride boolean,
      search boolean,
      sense_motive boolean,
      sleight_of_hand boolean,
      spellcraft boolean,
      spot boolean,
      survival boolean,
      swim boolean,
      tumble boolean,
      use_magic_device boolean,
      use_rope boolean

);

CREATE TABLE races(
    races_Id serial PRIMARY KEY,
    racesName VARCHAR(100), 
    subRacesName VARCHAR(100),
    strenght INT,
    dextrity INT,
    consitution INT,
    intelligence INT,
    wisdom INT,
    charisma INT,
    appraise INT,
    balance INT,
    bluff INT,
    climb INT,
    concentration INT,
    craft INT,
    decipher_script INT,
    diplomacy INT,
    disable_device INT,
    disguise INT,
    escape_artist INT,
    gather_information INT,
    handle_animal INT,
    heal INT,
    intimidate INT,
    jump INT,
    knowledge INT,
    listen INT,
    move_silently INT,
    perform INT,
    profession INT,
    ride INT,
    search INT,
    sense_motive INT,
    sleight_of_hand INT,
    speak_language VARCHAR(100),
    spellcraft INT,
    spot INT,
    survival INT,
    swim INT,
    tumble INT,
    use_magic_device INT,
    use_rope INT    

);

CREATE TABLE skills(
    skills_Id serial PRIMARY KEY,
    skillsName VARCHAR(50)
);