INSERT INTO public.skills  (skillsName) VALUES('Appraise');
INSERT INTO public.skills  (skillsName) VALUES('Balance');
INSERT INTO public.skills  (skillsName) VALUES('Bluff');
INSERT INTO public.skills  (skillsName) VALUES('Climb');
INSERT INTO public.skills  (skillsName) VALUES('Concentration');
INSERT INTO public.skills  (skillsName) VALUES('Craft');
INSERT INTO public.skills  (skillsName) VALUES('Decipher Script');
INSERT INTO public.skills  (skillsName) VALUES('Diplomacy');
INSERT INTO public.skills  (skillsName) VALUES('Disable Device');
INSERT INTO public.skills  (skillsName) VALUES('Disguise');
INSERT INTO public.skills  (skillsName) VALUES('Escape Artist');
INSERT INTO public.skills  (skillsName) VALUES('Gather Information');
INSERT INTO public.skills  (skillsName) VALUES('Handle Animal');
INSERT INTO public.skills  (skillsName) VALUES('Heal');
INSERT INTO public.skills  (skillsName) VALUES('Intimidate');
INSERT INTO public.skills  (skillsName) VALUES('Jump');
INSERT INTO public.skills  (skillsName) VALUES('Knowledge');
INSERT INTO public.skills  (skillsName) VALUES('Listen');
INSERT INTO public.skills  (skillsName) VALUES('Move Silently');
INSERT INTO public.skills  (skillsName) VALUES('Perform');
INSERT INTO public.skills  (skillsName) VALUES('Profession');
INSERT INTO public.skills  (skillsName) VALUES('Ride');
INSERT INTO public.skills  (skillsName) VALUES('Search');
INSERT INTO public.skills  (skillsName) VALUES('Sense Motive');
INSERT INTO public.skills  (skillsName) VALUES('Sleight Of Hand');
INSERT INTO public.skills  (skillsName) VALUES('Speak Language');
INSERT INTO public.skills  (skillsName) VALUES('Spellcraft');
INSERT INTO public.skills  (skillsName) VALUES('Spot');
INSERT INTO public.skills  (skillsName) VALUES('Survival');
INSERT INTO public.skills  (skillsName) VALUES('Swim');
INSERT INTO public.skills  (skillsName) VALUES('Tumble');
INSERT INTO public.skills  (skillsName) VALUES('Use Magic Device');
INSERT INTO public.skills  (skillsName) VALUES('Use Rope');