import { Abilitys } from "../../Abilitys/Interface";
import { ArmorClass } from "../../Armor/interface/ArmorInterface";
import { AttackRoll } from "../../Attack/AttackRoll/interface";
import { DamageBonus } from "../../Attack/DamageBonus/interface";
import { ClassPcLevel } from "../../ClassPc/Interface/ClassPcLevel";
import { Feat, FeatsTypeEnum } from "../../Feats/Interface/FeatInterface";
import { Item, SpecialAttacks } from "../../interfaces";
import { SpecialAbilities } from "../../Race/Interfaces";
import { SavingThrow } from "../../Saving/interface";
import { PrerequisiteSkills } from "../../Skills/interface/PrerequisiteSkills";
import { Speed } from "../../Speed/interface";
import { ModifierBonus } from "./ModifierBonus";
import { ModifierEnum } from "./ModifierEnum";

export type Prerequisite = {
  id: number;
  abilitys?: Abilitys;
  feats?: Feat[];
  featType?: FeatsTypeEnum[];
  caster?: [];
  bab?: Number;
  attackRoll?: ModifierBonus[];
  damageBonus?: ModifierBonus[];
  initiative?: Number;
  speed?: Speed;
  spaceReach?: string;
  savingThrow?: ModifierBonus[];
  specialAttacks?: SpecialAttacks;
  specialAbilities?: SpecialAbilities[];
  skillStudy?: PrerequisiteSkills[];
  armorClass?: ModifierBonus[];
  armorType?: ModifierEnum;
  weaponType?: ModifierEnum;
  schools?: string[];
  classPc?: ClassPcLevel[];
  items?: Item[];
  numberOfDomains?: number;
  text?: string;
};
