INSERT INTO public.skills VALUES(0, 'Appraise');
INSERT INTO public.skills VALUES(1, 'Balance');
INSERT INTO public.skills VALUES(2, 'Bluff');
INSERT INTO public.skills VALUES(3, 'Climb');
INSERT INTO public.skills VALUES(4, 'Concentration');
INSERT INTO public.skills VALUES(5, 'Craft');
INSERT INTO public.skills VALUES(6, 'Decipher Script');
INSERT INTO public.skills VALUES(7, 'Diplomacy');
INSERT INTO public.skills VALUES(8, 'Disable Device');
INSERT INTO public.skills VALUES(9, 'Escape Artist');
INSERT INTO public.skills VALUES(10, 'Gather Information');
INSERT INTO public.skills VALUES(11, 'Handle Animal');
INSERT INTO public.skills VALUES(12, 'Heal');
INSERT INTO public.skills VALUES(13, 'Intimidate');
INSERT INTO public.skills VALUES(14, 'Jump');
INSERT INTO public.skills VALUES(15, 'Knowledge');
INSERT INTO public.skills VALUES(16, 'Listen');
INSERT INTO public.skills VALUES(17, 'Move Silently');
INSERT INTO public.skills VALUES(18, 'Profession');
INSERT INTO public.skills VALUES(19, 'RskillsIde');
INSERT INTO public.skills VALUES(20, 'Search');
INSERT INTO public.skills VALUES(21, 'Sense Motive');
INSERT INTO public.skills VALUES(22, 'Sleight Of Hand');
INSERT INTO public.skills VALUES(23, 'Speak Language');
INSERT INTO public.skills VALUES(24, 'Spellcraft');
INSERT INTO public.skills VALUES(25, 'Spot');
INSERT INTO public.skills VALUES(26, 'Survival');
INSERT INTO public.skills VALUES(27, 'Swim');
INSERT INTO public.skills VALUES(28, 'Tumble');
INSERT INTO public.skills VALUES(29, 'Use Magic Device');
INSERT INTO public.skills VALUES(30, 'Use Rope');