INSERT INTO public.skills (skillsId, skillsName) VALUES(0, 'Appraise');
INSERT INTO public.skills (skillsId, skillsName) VALUES(1, 'Balance');
INSERT INTO public.skills (skillsId, skillsName) VALUES(2, 'Bluff');
INSERT INTO public.skills (skillsId, skillsName) VALUES(3, 'Climb');
INSERT INTO public.skills (skillsId, skillsName) VALUES(4, 'Concentration');
INSERT INTO public.skills (skillsId, skillsName) VALUES(5, 'Craft');
INSERT INTO public.skills (skillsId, skillsName) VALUES(6, 'Decipher Script');
INSERT INTO public.skills (skillsId, skillsName) VALUES(7, 'Diplomacy');
INSERT INTO public.skills (skillsId, skillsName) VALUES(8, 'Disable Device');
INSERT INTO public.skills (skillsId, skillsName) VALUES(9, 'Escape Artist');
INSERT INTO public.skills (skillsId, skillsName) VALUES(10, 'Gather Information');
INSERT INTO public.skills (skillsId, skillsName) VALUES(11, 'Handle Animal');
INSERT INTO public.skills (skillsId, skillsName) VALUES(12, 'Heal');
INSERT INTO public.skills (skillsId, skillsName) VALUES(13, 'Intimidate');
INSERT INTO public.skills (skillsId, skillsName) VALUES(14, 'Jump');
INSERT INTO public.skills (skillsId, skillsName) VALUES(15, 'Knowledge');
INSERT INTO public.skills (skillsId, skillsName) VALUES(16, 'Listen');
INSERT INTO public.skills (skillsId, skillsName) VALUES(17, 'Move Silently');
INSERT INTO public.skills (skillsId, skillsName) VALUES(18, 'Profession');
INSERT INTO public.skills (skillsId, skillsName) VALUES(19, 'RskillsIde');
INSERT INTO public.skills (skillsId, skillsName) VALUES(20, 'Search');
INSERT INTO public.skills (skillsId, skillsName) VALUES(21, 'Sense Motive');
INSERT INTO public.skills (skillsId, skillsName) VALUES(22, 'Sleight Of Hand');
INSERT INTO public.skills (skillsId, skillsName) VALUES(23, 'Speak Language');
INSERT INTO public.skills (skillsId, skillsName) VALUES(24, 'Spellcraft');
INSERT INTO public.skills (skillsId, skillsName) VALUES(25, 'Spot');
INSERT INTO public.skills (skillsId, skillsName) VALUES(26, 'Survival');
INSERT INTO public.skills (skillsId, skillsName) VALUES(27, 'Swim');
INSERT INTO public.skills (skillsId, skillsName) VALUES(28, 'Tumble');
INSERT INTO public.skills (skillsId, skillsName) VALUES(29, 'Use Magic Device');
INSERT INTO public.skills (skillsId, skillsName) VALUES(30, 'Use Rope');