version: latest
services:
  db:
    image: postgres:10.5
    # image: postgres
    restart: always
    container_name: my_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5433:5432'
    networks:
      - backend
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data

  api:
    image: skalord88/api:latest
    depends_on:
      - db
    networks:
      - backend
    ports:
      - '8080:8080'
    #   - '5005:5005'
    # command: ['java', '-Xdebug', '-Xrunjdwp:transport=dt_socket,server=y,address=5005,suspend=n', '-jar', 'app.jar']

networks:
  backend:

volumes:
  postgres_data: