# version: '3.9'
services:
  db:
    image: postgres:10.5
    restart: always
    container_name: my_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    networks:
      - backend
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data

  api:
    image: skalord88/api:latest
    depends_on:
      - db
    networks:
      - backend
    ports:
      - '8080:8080'

networks:
  backend:

volumes:
  postgres_data: