version: '3.9'
services:
  postgres:
    image: postgres:10.5
    container_name: db_ded_card
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    networks:
      - backend
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  api:
    build:
      context: C:/Users/skalo/OneDrive/Documenti/ded_card/api
      dockerfile: Dockerfile
    container_name: back_ded_card
    restart: always
    depends_on:
      - postgres
    networks:
      - backend
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

networks:
  backend:
    driver: bridge


    # command: ["./wait-for-it.sh", "postgres:5432", "--", "liquibase", "--changeLogFile=changelog.xml", "--url=jdbc:postgresql://postgres:5432/postgres", "--username=postgres", "--password=postgres", "update"]



  # frontend:
  #   build:
  #     context: C:\Users\skalo\OneDrive\Documenti\ded_card\ded_web_app
  #     dockerfile: Dockerfile
  #   restart: always
  #   ports:
  #     - '3000:3000'
  #   environment:
  #     - REACT_APP_API_URL=http://backend:8080/api
