services:
  db:
    image: postgres:18
    restart: always
    container_name: my_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    networks:
      - backend
    volumes:
      - pgdata:/var/lib/postgresql

  api:
    image: api:latest
    depends_on:
      - db
    networks:
      - backend
    ports:
      - "8080:8080"

networks:
  backend:

volumes:
  pgdata:
