version: '3.9'
services:
  db:
    image: postgres:10.5
    restart: always
    container_name: my_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    networks:
      - backend
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data

  api:
    image: skalord88/api:latest
    depends_on:
      - db
    networks:
      - backend
    ports:
      - '8080:8080'
    # environment:
    #   SPRING_DATASOURCE_URL: jdbc:postgresql://dedpostgres.cb8k82mms3o8.eu-central-1.rds.amazonaws.com:5432/postgres
      # SPRING_DATASOURCE_USERNAME: postgres
      # SPRING_DATASOURCE_PASSWORD: postgres

  # frontend:
  #   image: skalord88/api-frontend:latest
  #   restart: always
  #   networks:
  #     - backend
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - api

networks:
  backend:
    # driver: bridge  

volumes:
  postgres_data: